/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package myjava;

import com.rabbitmq.client.*;

public class App {
    private static final String EXCHANGE_NAME = "direct_exchange";
    private static final String QUEUE_NAME = "hello";

    public static void main(String[] argv) throws Exception {
        ConnectionFactory factory = new ConnectionFactory();
        factory.setHost("localhost"); // RabbitMQ 服务的主机名或 IP 地址
        factory.setUsername("guest"); // RabbitMQ 用户名
        factory.setPassword("guest"); // RabbitMQ 密码

        try (Connection connection = factory.newConnection();
                Channel channel = connection.createChannel()) {

            channel.queueDeclare(QUEUE_NAME, false, false, false, null);
            // channel.queueBind(QUEUE_NAME, EXCHANGE_NAME, "");

            System.out.println(" [*] Waiting for messages. To exit press Ctrl+C");

            DeliverCallback deliverCallback = (consumerTag, delivery) -> {
                String message = new String(delivery.getBody(), "UTF-8");
                System.out.println(" [x] Received '" + message + "'");
            };

            channel.basicConsume(QUEUE_NAME, true, deliverCallback, consumerTag -> {
            });
            System.in.read();

        }
    }
}
